"""relationship

Revision ID: 23c6c50cec72
Revises: 19f26d89d282
Create Date: 2024-02-15 13:16:30.585657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c6c50cec72'
down_revision: Union[str, None] = '19f26d89d282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'type_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('type_document', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
